export default {
  bins: [
    {
      fileName: "hutt.jpg",
      slug: "hutt-city",
      localAuthorityCode: "HCC",
      collectionDate: "22 April 2022",
      contributorHandle: "@mattlane",
      contributorURL: "https://twitter.com/mattlane",
      colour: "1-green-red",
      councilName: "Hutt City",
    },
    {
      fileName: "ruapara.jpg",
      slug: "new-plymouth-district",
      localAuthorityCode: "NPD",
      collectionDate: "22 April 2022",
      contributorHandle: "@mattlane",
      contributorURL: "https://twitter.com/mattlane",
      colour: "1-green-red",
      councilName: "New Plymouth District",
    },
    {
      fileName: "south-taranaki.jpg",
      slug: "south-taranaki-district",
      localAuthorityCode: "STD",
      collectionDate: "22 April 2022",
      contributorHandle: "@mattlane",
      contributorURL: "https://twitter.com/mattlane",
      colour: "1-green-red",
      councilName: "South Taranaki District",
    },
    {
      fileName: "wellington.jpg",
      slug: "wellington-city",
      localAuthorityCode: "WCC",
      collectionDate: "27 April 2022",
      contributorHandle: "@freylucas",
      contributorURL: "https://twitter.com/freylucas",
      colour: "4-black-yellow",
      councilName: "Wellington City",
    },
    {
      fileName: "invercargill-city.jpg",
      slug: "invercargill-city",
      localAuthorityCode: "ICC",
      collectionDate: "29 April 2022",
      contributorHandle: "Mark Radcliffe",
      colour: "2-black-red",
      councilName: "Invercargill City",
    },
    {
      fileName: "palmerston-north-city.jpg",
      slug: "palmerston-north-city",
      localAuthorityCode: "PNC",
      collectionDate: "29 April 2022",
      contributorHandle: "@donkey",
      contributorURL: "https://twitter.com/donkey",
      colour: "3-black-orange",
      councilName: "Palmerston North City",
    },
    {
      fileName: "hamilton.jpg",
      slug: "hamilton-city",
      localAuthorityCode: "HCC",
      collectionDate: "29 April 2022",
      colour: "1-green-red",
      councilName: "Hamilton City",
    },
    {
      fileName: "selwyn.jpg",
      slug: "selwyn-district",
      localAuthorityCode: "SDC",
      collectionDate: "2 May 2022",
      contributorHandle: "@samrag",
      contributorURL: "https://twitter.com/samrag",
      colour: "2-black-red",
      councilName: "Selwyn District",
    },
    {
      fileName: "christchurch.jpg",
      slug: "christchurch-city",
      localAuthorityCode: "CCC",
      collectionDate: "6 May 2022",
      contributorHandle: "@jnbrl",
      contributorURL: "https://twitter.com/jnbrl",
      colour: "2-black-red",
      councilName: "Christchurch City",
    },
  ],
};
