export default {
  bins: [
    {
      fileName: "hutt.jpg",
      slug: "hutt-city",
      localAuthorityCode: "HCC",
      collectionDate: "22 April 2022",
      contributorHandle: "@mattlane",
      contributorURL: "https://twitter.com/mattlane",
      colour: "green",
      councilName: "Hutt City",
    },
    {
      fileName: "ruapara.jpg",
      slug: "new-plymouth-district",
      localAuthorityCode: "NPD",
      collectionDate: "22 April 2022",
      contributorHandle: "@mattlane",
      contributorURL: "https://twitter.com/mattlane",
      colour: "green",
      councilName: "New Plymouth District",
    },
    {
      fileName: "south-taranaki.jpg",
      slug: "south-taranaki-district",
      localAuthorityCode: "STD",
      collectionDate: "22 April 2022",
      contributorHandle: "@mattlane",
      contributorURL: "https://twitter.com/mattlane",
      colour: "green",
      councilName: "South Taranaki District",
    },
    {
      fileName: "wellington.jpg",
      slug: "wellington-city",
      localAuthorityCode: "WCC",
      collectionDate: "27 April 2022",
      contributorHandle: "@freylucas",
      contributorURL: "https://twitter.com/freylucas",
      colour: "black",
      councilName: "Wellington City",
    },
    {
      fileName: "invercargill-city.jpg",
      slug: "invercargill-city",
      localAuthorityCode: "ICC",
      collectionDate: "29 April 2022",
      contributorHandle: "Mark Radcliffe",
      colour: "black",
      councilName: "Invercargill City",
    },
    {
      fileName: "palmerston-north-city.jpg",
      slug: "palmerston-north-city",
      localAuthorityCode: "PNC",
      collectionDate: "29 April 2022",
      contributorHandle: "@donkey",
      contributorURL: "https://twitter.com/donkey",
      colour: "black",
      councilName: "Palmerston North City",
    },
    {
      fileName: "hamilton.jpg",
      slug: "hamilton-city",
      localAuthorityCode: "HCC",
      collectionDate: "29 April 2022",
      colour: "green",
      councilName: "Hamilton City",
    },
    {
      fileName: "selwyn1.jpg",
      slug: "selwyn-district",
      localAuthorityCode: "SDC",
      collectionDate: "2 May 2022",
      contributorHandle: "@samrag",
      contributorURL: "https://twitter.com/samrag",
      colour: "black",
      councilName: "Selwyn District",
    },
  ],
};
